# Generated by Django 2.1.5 on 2024-05-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240405_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='level',
        ),
    ]
