# Generated by Django 5.0 on 2024-07-01 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_player_level_player_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('slogan', models.CharField(max_length=127)),
                ('description', models.CharField(max_length=2047)),
                ('members_count', models.IntegerField(default=1)),
                ('lieder', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lieder', to='users.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group'),
        ),
    ]
