# Generated by Django 5.0 on 2024-07-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_group_player_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='lieder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lieder_group', to='users.player'),
        ),
    ]
