stages:
  - build
  - publish
  - deploy

  
variables:
  DOCKER_IMAGE_NAME: "sok"

build:
  only: 
    - master
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
  tags:
    - windows
  image:
    docker:stable

publish:
  stage: publish
  only:
    - master
  script:
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $DOCKER_IMAGE_NAME
  tags:
    - windows
  image:
    docker:stable

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - CONTAINER_NAME='games_container'
    - CID=$(docker ps -q -f status=running -f name=^/${CONTAINER_NAME}$)
    - if [ ! "${CID}" ]; then
    - echo "Container doesn't exist"
    - docker run -d -p 8000:8000 --name games_container $DOCKER_IMAGE_NAME
    - fi
    - if [ "${CID}" ]; then
    - echo "Container exists"
    - echo "Removing container"
    - docker rm games_container -f
    - echo "Creating new container"
    - docker run -d -p 8000:8000 --name games_container $DOCKER_IMAGE_NAME
    - fi
    - unset CID
    - echo "Container is running."
  tags:
    - windows
  image:
    docker:stable